### ISSUE TITLE
Inconsistent repo structure

### ISSUE THREAD

**Issue by lovesh** [hyperledger/ursa-rfcs#16]
The repo structure is inconsistent, it has verifiable encryption RFC at root level and other RFCs inside `text` folder.Should we consider the aries-rfcs repo structure https://github.com/hyperledger/aries-rfcs? Assigning numbers can be confusing for the author as there is no guarantee of the order of merging of RFCs. Maybe in the long run, have a script that runs at merge time and assigns the right number to the RFC

**Comment by brentzundel** [comment]
Aries RFCs are assigned the number of the pull request they are submitted with, so that removes the ordering problem, but does add gaps in the RFC numbering.

**Comment by danintel** [comment]
Hyperledger Sawtooth RFCs uses the PR# for the RFC number, so no reassigning/editing is needed at merge.
